In [1]:
name = 'Gurkirpal'
age = 34
z = (f'{name} is {age} years old')
print(z)

Gurkirpal is 34 years old


In [2]:
z

'Gurkirpal is 34 years old'

In [3]:
z[-3]

'o'

In [4]:
z[4:17]

'irpal is 34 y'

In [5]:
z[::2]

'Gripli 4yasod'

In [6]:
z[2::]

'rkirpal is 34 years old'

In [7]:
ml = [1,2,3,'a','b','c']
ml

[1, 2, 3, 'a', 'b', 'c']

In [8]:
ml.append('d')
ml

[1, 2, 3, 'a', 'b', 'c', 'd']

In [9]:
ml[1] = 'New'
ml

[1, 'New', 3, 'a', 'b', 'c', 'd']

In [10]:
a = [1,1,1,2,3,4,4,455,5,5,6,7]
set(a)

{1, 2, 3, 4, 5, 6, 7, 455}

In [11]:
a = [1,2,3,4,5]
for num in a:
    print(num)

1
2
3
4
5


In [12]:
for num in range(1,11):
    print(num)
num = num + 1

1
2
3
4
5
6
7
8
9
10


In [13]:
i =1
while i < 5:
    print(i)
    i = i + 1

1
2
3
4


In [14]:
x = [1,2,3,4]

In [15]:
out = []
for num in x:
    out.append(num**2)
print(out)

[1, 4, 9, 16]


In [16]:
def num(z):
    print(z)

In [17]:
num('hello')

hello


In [18]:
def num(z):
    print(z + 'pal')

In [19]:
num('hello ')

hello pal


In [20]:
def sq(num):
    return num**2

In [21]:
sq(7)

49

In [22]:
x = []
z = range(1,6)
for num in z:
    x.append(num**2)
print(x)

[1, 4, 9, 16, 25]


In [23]:
t = lambda var : var**2

In [24]:
t(3)

9

In [25]:
s = 'my name is kirpal'
s.split()

['my', 'name', 'is', 'kirpal']

In [26]:
s.split('a')

['my n', 'me is kirp', 'l']

In [27]:
d = {'apples': 12, 'banana':23}

In [28]:
d.values()

dict_values([12, 23])

In [29]:
d.keys()

dict_keys(['apples', 'banana'])

In [30]:
planet = 'Earth'
diameter =12742
print(f'The diameter of {planet} is {diameter} kilometers')

The diameter of Earth is 12742 kilometers


In [31]:
def finddog(s):
    return 'dog' in s.lower().split()

In [32]:
finddog('I have white dog')

True

In [33]:
def finddog(s):
    count = 0
    for word in s.lower().split():
        if word == 'dog':
            count = count + 1
    return count

In [34]:
finddog('This dog runs fater than other dog')

2

### Numpy

In [35]:
import numpy as np

In [36]:
ml = [1,2,3,4]
np.array(ml)

array([1, 2, 3, 4])

In [37]:
ml1 = [[1,2,3],[4,5,6],[7,8,9]] 
np.array(ml1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [41]:
a = [1,2,3,4]
z=np.array(a)
z

array([1, 2, 3, 4])

In [42]:
z.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [43]:
np.random.randint(1,10,5)

array([6, 9, 2, 3, 4])

In [44]:
np.random.randn(2,2)

array([[0.53248957, 0.84478543],
       [0.56310949, 1.04091343]])

In [45]:
np.random.rand(2)

array([0.09677256, 0.29621848])

In [46]:
z = np.random.randint(1,100,20)
z

array([38, 55, 21, 10,  8, 20, 54, 90, 70, 79, 79,  5, 16, 60, 68, 90, 76,
       39, 95, 29])

In [47]:
z.max()

95

In [48]:
z.min()

5

In [49]:
z = np.arange(0,11)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
z[8]

8

In [51]:
z[5] = 45

In [52]:
z

array([ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10])

In [53]:
z

array([ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10])

In [54]:
z **2

array([   0,    1,    4,    9,   16, 2025,   36,   49,   64,   81,  100],
      dtype=int32)

In [55]:
z/4

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  , 11.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ])

In [56]:
z/z

<ipython-input-56-53ab6594616a>:1: RuntimeWarning: invalid value encountered in true_divide
  z/z


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
np.exp(z)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 3.49342711e+19, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [58]:
np.sin(z)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        0.85090352, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [59]:
np.log(z)

<ipython-input-59-d550cedc7d1d>:1: RuntimeWarning: divide by zero encountered in log
  np.log(z)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       3.80666249, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### Pandas

In [61]:
import pandas as pd